feature/php-pre-challenge1
giyana/codegym-php pull request #2
Opened 2021-05-13 13:32 UTC by giyana

2021-05-13 13:33 UTC, giyana commented
デバッグ済

2021-05-14 07:23 UTC, Yuzunoha commented on html/php-pre-challenge1/index.php
> +            print("<br>");
`print("<br>");` はソース全体で1個にできるはずです！改善してみましょう。

2021-05-14 07:25 UTC, Yuzunoha commented on html/php-pre-challenge1/index.php
> +    if ($i % 3 == 0) {
曖昧な比較(等価演算子) `==` ではなく、
厳密な比較(同値演算子) `===` を使いましょう！
ソースコード全体を改善してください。

2021-05-14 07:48 UTC, Yuzunoha requested changes
出力結果に関してはOKです！
ソースコードの改善のコメントをしているのでご確認ください～

2021-05-14 10:21 UTC, TomoakiTANAKA commented
確認事項
- [x] ゆずのはさんの指摘事項の修正確認
- [x] 動作チェック
- [x] コードチェック -> 修正不要な指摘あり。あとで目を通しておいてください。
- [ ]

2021-05-14 10:25 UTC, TomoakiTANAKA commented on html/php-pre-challenge1/index.php
> +        }
[info：修正不要]

この規模であれば見通しつくくので問題はないです。
ただ一般論として、ifのネストをできる限り避けるほうが良いです。

コードを書く時に無用はifを作っていないか？など考えてみましょう。

理由：ネストが深くなるとコードの見通しが悪くなるため => 見通しが悪いとコードの変更をする時に把握が大変 => 不具合を入れ込む可能性があがる

```php
if ($i % 15 === 0) {
  // 3 かつ 5の倍数
} else if ($i % 3 === 0) {
  // 3の倍数
} else if ($i % 5 ===0) {
  // 5の倍数
}  else {
  // その他
}
```

2021-05-14 10:25 UTC, TomoakiTANAKA commented
LGTM

2021-05-14 10:27 UTC, merged